-- StarqueZZ v2 · 0004_libraries.sql
-- Global, curated, read-only libraries. Drafted with LLM help, curated by
-- hand. No user-generated content pipeline, ever (AGENT_BRIEF §6).

-- ============================================================ Habit Library
-- why_it_matters: honest, lightly worded — never citation theater.
insert into habit_library
  (name, icon, kid_label, category, age_min, age_max, why_it_matters, sources_note, suggested_block, mastery_signal) values
-- Body
('Brush teeth', 'tooth', 'Brush teeth', 'body', 4, 10,
 'Twice-daily brushing in childhood sets the habit that protects adult teeth — it''s easier to keep than to start later.',
 'AAPD oral health guidelines', 'morning', 'Does it without being reminded for ~3 weeks'),
('Get dressed by myself', 'shirt', 'Get dressed', 'body', 4, 7,
 'Dressing independently builds fine motor skills and is one of the first "I can do it myself" wins of the day.',
 'CDC developmental milestones', 'morning', 'Fully dressed without help or reminders for 2 weeks'),
('Eat breakfast', 'bowl', 'Eat breakfast', 'body', 4, 10,
 'Kids who eat breakfast concentrate better through the school morning — the brain runs on it.',
 'Adolphus et al. 2013 review', 'morning', 'Sits down to breakfast on their own schedule'),
('Drink water', 'water', 'Drink water', 'body', 4, 10,
 'Most kids drink less water than they need; a daily cue builds the default that lasts.',
 'AAP hydration guidance', 'afternoon', 'Reaches for water without prompting'),
('Outdoor play', 'ball', 'Play outside', 'body', 4, 10,
 'An hour of daily movement supports sleep, mood, and growing bodies — outside time does double duty for eyes and energy.',
 'WHO activity guidelines for children', 'afternoon', 'Heads out on their own most days'),
('Bath or shower', 'drop', 'Bath time', 'body', 4, 10,
 'An evening wash is a reliable sleep cue — the body learns that warm water means winding down.',
 'Sleep hygiene literature', 'evening', 'Starts bath time without a fuss for 3 weeks'),
('To bed on time', 'bed', 'Bedtime', 'body', 4, 10,
 'School-age kids need 9–12 hours; a consistent bedtime does more for mood and learning than almost anything else.',
 'AASM pediatric sleep recommendations', 'evening', 'In bed at the agreed time without negotiation'),
-- Mind
('Reading time', 'book', 'Reading time', 'mind', 5, 10,
 'Daily reading is one of the strongest predictors of later literacy — ten minutes a day compounds.',
 'OECD reading engagement studies', 'evening', 'Picks up a book unprompted most days'),
('Practice an instrument', 'music', 'Music practice', 'mind', 6, 10,
 'Short, regular practice beats long rare sessions — daily minutes are how an instrument becomes part of who they are.',
 'Deliberate practice literature (Ericsson)', 'afternoon', 'Practices without being asked for ~3 weeks'),
('Homework first', 'pencil', 'Homework', 'mind', 6, 10,
 'Doing homework at the same time each day removes the daily battle — the routine carries the effort.',
 'Habit formation research (Lally et al.)', 'afternoon', 'Starts homework on their own at the usual time'),
('Curiosity question', 'bulb', 'Ask a big question', 'mind', 5, 10,
 'Asking one "I wonder why…" a day keeps curiosity a habit, not an accident — and gives you great dinner conversations.',
 'Curiosity & learning research (Engel)', 'evening', 'Brings questions to you without the card'),
('Draw or make something', 'paint', 'Make something', 'mind', 4, 10,
 'Open-ended making — drawing, building, crafting — is how kids practice ideas. A little every day keeps the maker muscle warm.',
 'Creative development literature', 'afternoon', 'Has their own ongoing projects'),
-- Space
('Make the bed', 'bed-made', 'Make my bed', 'space', 5, 10,
 'A small, visible win first thing in the morning — it starts the day with "done" instead of "told to".',
 'Habit stacking literature', 'morning', 'Bed made before breakfast without reminders'),
('Pack the school bag', 'backpack', 'Pack my bag', 'space', 6, 10,
 'Packing their own bag the night before turns morning chaos into a calm start — and forgotten homework into a rarity.',
 'Executive function development research', 'evening', 'Bag ready at the door every school night'),
('Tidy the toys', 'blocks', 'Tidy up', 'space', 4, 8,
 'A five-minute tidy teaches that spaces reset — caring for belongings is a form of ownership.',
 'Montessori practical life principles', 'evening', 'Tidies after play without being asked'),
('Set the table', 'fork', 'Set the table', 'space', 5, 10,
 'A real contribution to family life — kids who have a genuine job feel like genuine members of the household.',
 'Family contribution research (Rende)', 'evening', 'Does their job without prompting'),
('Water the plants', 'plant', 'Water plants', 'space', 5, 10,
 'Caring for a living thing on a schedule builds gentle responsibility — the plant notices when you forget.',
 'Responsibility development literature', 'morning', 'Remembers their plant most days unaided'),
-- Heart
('Say one kind thing', 'heart', 'Kind words', 'heart', 4, 10,
 'Naming one kind thing to say each day makes kindness deliberate — and noticed kindness tends to multiply.',
 'Prosocial behavior research', 'evening', 'Kind words show up on their own'),
('Gratitude moment', 'sparkle-heart', 'Best thing today', 'heart', 5, 10,
 'Naming one good thing from the day trains attention toward the good — a small, durable happiness habit.',
 'Gratitude interventions (Emmons & McCullough)', 'evening', 'Shares their "best thing" at dinner unprompted'),
('Help a family member', 'hands', 'Help someone', 'heart', 5, 10,
 'One small act of help a day teaches that family is a team — and that they have something real to offer.',
 'Family contribution research', 'afternoon', 'Offers help without being asked'),
('Feed the pet', 'paw', 'Feed the pet', 'heart', 5, 10,
 'A pet''s breakfast depending on you is responsibility a kid can feel — hungry eyes are honest feedback.',
 'Pet care & empathy literature', 'morning', 'The pet never has to wait'),
('Share screen-free play', 'dice', 'Play together', 'heart', 4, 10,
 'Fifteen minutes of sibling or family play without screens builds the negotiation muscles kids use everywhere else.',
 'Play research (Gray)', 'afternoon', 'Initiates shared play on their own');

-- ============================================================ Adventure Library
-- Each entry runnable by any parent after reading three sentences.
-- At-home, zero-cost entries are first-class citizens.
insert into library_activities
  (name, illustration, explainer, prep, duration_min, energy, age_min, age_max, cost, location_type, suggested_tier) values
-- home, free (feed Tier 1 + fallback)
('Treasure Hunt in the Dark', 'flashlight',
 'Hide 5 small things around the house. Lights off. Give the kid a flashlight and a list. Hunt.',
 'Flashlight, 5 objects', 30, 'indoor', 5, 9, 'free', 'home', 1),
('Blanket Fort Night', 'fort',
 'Build a fort out of blankets and chairs together. Crawl in with snacks and a book or flashlight stories.',
 'Blankets, chairs, fairy lights optional', 45, 'indoor', 4, 9, 'free', 'home', 1),
('Pancake Morning', 'pancake',
 'A slow weekend breakfast where the kid is head chef. They mix, you handle the pan, everyone decorates their own stack.',
 'Pancake ingredients', 40, 'indoor', 4, 10, 'cheap', 'home', 0),
('Living-room Campout', 'tent',
 'Pitch a real tent (or fort) in the living room and sleep in it. Torch shadows, whispered stories, breakfast in the tent.',
 'Tent or blankets, sleeping bags', 60, 'indoor', 5, 10, 'free', 'home', 3),
('Movie Night — Kid''s Pick', 'popcorn',
 'The kid picks the film, you make it cinema: tickets they draw, popcorn, lights off. Phones in another room.',
 'Popcorn, paper for tickets', 100, 'indoor', 4, 10, 'cheap', 'home', 1),
('Board Game Tournament', 'dice',
 'Best of three games of the kid''s choice, with a hand-drawn bracket and a silly trophy for the winner.',
 'Board games, paper for the bracket', 60, 'indoor', 5, 10, 'free', 'home', 1),
('Baking Day', 'cupcake',
 'Pick a recipe together, shop the cupboard, and bake. The kid measures and mixes; you do the oven. Eat warm.',
 'Baking ingredients', 75, 'indoor', 4, 10, 'cheap', 'home', 1),
('Dance Party Kitchen Disco', 'disco',
 'Push the chairs back, kid DJs three songs, you DJ three. Dance like nobody''s filming, because nobody is.',
 'A speaker', 20, 'indoor', 4, 9, 'free', 'home', 1),
('Paper Plane Championship', 'plane',
 'Fold five different plane designs each, then run distance, accuracy, and trick contests down the hallway.',
 'Paper, tape for target circles', 30, 'indoor', 5, 10, 'free', 'home', 1),
('Home Science Lab', 'flask',
 'Three kitchen experiments: volcano (vinegar + baking soda), invisible ink (lemon), dancing raisins (fizzy water). Lab coats optional, goggles cool.',
 'Vinegar, baking soda, lemon, fizzy water', 45, 'indoor', 5, 10, 'cheap', 'home', 2),
('Story Swap Night', 'book-night',
 'Lights low. You tell a story from your childhood, they invent one back. One rule: every story needs a hero and a disaster.',
 'Nothing', 25, 'indoor', 4, 10, 'free', 'home', 1),
('Indoor Picnic', 'basket',
 'Spread the picnic blanket on the living-room floor, make sandwiches together, and eat dinner as if the carpet were grass. Weather-proof.',
 'Blanket, sandwich things', 40, 'indoor', 4, 8, 'free', 'home', 1),
('Lego Grand Build', 'blocks',
 'One shared build, one ridiculous brief — "a house for a dragon who loves baths". Build for an hour, then tour each other through it.',
 'Building blocks', 60, 'indoor', 4, 10, 'free', 'home', 1),
('Cook Dinner Together', 'chef',
 'The kid picks the menu (within reason), wears the apron, and runs the kitchen with you as sous-chef. Family eats what they made.',
 'Dinner ingredients', 60, 'indoor', 6, 10, 'cheap', 'home', 2),
('Backyard Stargazing', 'stars',
 'Blankets out after dark. Find the moon, count satellites, invent your own constellations and name them after the family.',
 'Blankets, hot chocolate optional', 30, 'outdoor', 5, 10, 'free', 'home', 1),
-- out and about, mostly free
('Playground Expedition', 'swing',
 'Head to a playground with full attention: you''re not on a bench with a phone, you''re the monster who chases.',
 'Nothing', 60, 'outdoor', 4, 9, 'free', 'any playground', 1),
('New Playground Quest', 'map',
 'Visit a playground you''ve never been to. Rate it together out of ten: slides, climbability, swing quality. Keep a family ranking.',
 'Nothing', 75, 'outdoor', 4, 9, 'free', 'any playground', 2),
('Library Run', 'library',
 'A slow hour at the library. The kid picks any three books — no vetoes. Read the first one together over a snack after.',
 'Library card', 60, 'indoor', 4, 10, 'free', 'a library', 1),
('Bike Ride Together', 'bike',
 'Pick a destination worth pedalling to — a bakery, a pond, a big hill. Ride there together, snack, ride home.',
 'Bikes, helmets', 60, 'outdoor', 5, 10, 'free', 'a bike path', 1),
('Bookshop Trip', 'bookshop',
 'Browse a real bookshop and the kid picks one book to keep — their choice, your price cap. Read the opening pages over a drink nearby.',
 'Price cap agreed beforehand', 60, 'indoor', 5, 10, 'cheap', 'a bookshop', 2),
('Swimming Trip', 'swim',
 'A pool session that''s all play: races you lose, handstand contests, the big slide ten times. Hot snack after, hair still wet.',
 'Swim gear', 90, 'either', 4, 10, 'cheap', 'a pool', 2),
('Nature Scavenger Hunt', 'leaf',
 'Write a 10-item list together first — something red, a feather, a funny stick. Then hunt the park until the list is beaten.',
 'Paper list, a bag for finds', 60, 'outdoor', 4, 9, 'free', 'a park', 1),
('Sunrise or Sunset Mission', 'sunrise',
 'Pick a spot with a view and catch the sun doing its thing. Hot drinks in a thermos make it an expedition, not a walk.',
 'Thermos, blanket', 45, 'outdoor', 5, 10, 'free', 'a viewpoint', 2),
('Market Morning', 'market',
 'Wander a local market with a tiny budget the kid controls. They choose one thing for the family — dinner ingredient or small treasure.',
 'Small budget in cash', 60, 'outdoor', 5, 10, 'cheap', 'a market', 1),
('Kid Picks Friday Dinner', 'noodles',
 'The kid chooses where the family eats on Friday — their call, no vetoes within the agreed shortlist. They announce it at the table.',
 'Restaurant shortlist', 90, 'either', 5, 10, 'spendy', 'a restaurant', 2),
('Museum + Lunch Out', 'museum',
 'A museum morning at the kid''s pace — their three favorite rooms, not yours — then lunch out where they pick the table.',
 'Tickets if needed', 180, 'indoor', 5, 10, 'spendy', 'a museum', 3),
('Day Trip Adventure', 'train',
 'A whole day somewhere new — a train ride away or a long drive with the kid as co-pilot and snack master. Home tired and happy.',
 'Snacks, day plan', 360, 'either', 5, 10, 'spendy', 'a day-trip spot', 3),
('Treasure Hunt Dad Designs', 'scroll',
 'A real hunt with hand-drawn map, riddle clues and a buried (or hidden) prize box. Takes you an evening to set up; they''ll remember it for years.',
 'Map, 5–8 clues, a prize box', 90, 'either', 5, 10, 'cheap', 'home or a park', 3),
('Camping Trip', 'campfire',
 'A real night under canvas — tent, torches, campfire food, zero schedule. The deluxe version of the living-room campout.',
 'Camping gear, site booking', 720, 'outdoor', 6, 10, 'spendy', 'a campsite', 3),
('Art Gallery Sketch Walk', 'easel',
 'Take sketchbooks to a gallery. Each of you picks one artwork and copies it badly, then swap and guess which was which.',
 'Sketchbooks, pencils', 90, 'indoor', 6, 10, 'cheap', 'a gallery', 2);
